# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PadsElementScratch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 600)
        MainWindow.setMinimumSize(QtCore.QSize(811, 600))
        MainWindow.setMaximumSize(QtCore.QSize(811, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 25, 791, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layerChooseCombox = QtWidgets.QComboBox(self.centralwidget)
        self.layerChooseCombox.setGeometry(QtCore.QRect(8, 240, 121, 22))
        self.layerChooseCombox.setObjectName("layerChooseCombox")
        self.layerChooseCombox.addItem("")
        self.layerChooseCombox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 215, 141, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 141, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 266, 141, 20))
        self.label_3.setObjectName("label_3")
        self.chooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFileButton.setGeometry(QtCore.QRect(10, 290, 75, 31))
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.choosedFilePathTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.choosedFilePathTextEdit.setEnabled(False)
        self.choosedFilePathTextEdit.setGeometry(QtCore.QRect(100, 290, 691, 31))
        self.choosedFilePathTextEdit.setObjectName("choosedFilePathTextEdit")
        self.runningStatusTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.runningStatusTextEdit.setEnabled(True)
        self.runningStatusTextEdit.setGeometry(QtCore.QRect(100, 330, 691, 31))
        self.runningStatusTextEdit.setObjectName("runningStatusTextEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(13, 329, 81, 31))
        self.label_4.setObjectName("label_4")
        self.runningButton = QtWidgets.QPushButton(self.centralwidget)
        self.runningButton.setGeometry(QtCore.QRect(10, 370, 781, 51))
        self.runningButton.setObjectName("runningButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 425, 101, 21))
        self.label_5.setObjectName("label_5")
        self.runningResultTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.runningResultTextEdit.setEnabled(False)
        self.runningResultTextEdit.setGeometry(QtCore.QRect(10, 450, 791, 141))
        self.runningResultTextEdit.setObjectName("runningResultTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def keyPressEvent(self, QKeyEvent):
    #     print("A")
    #     print("按下：{}键, 程序结束".format(str(QKeyEvent.key())))
    #     if QKeyEvent.key() == Qt.Key_Escape:
    #         print("Done")
    #         sys.exit(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow",
                                                   "【注意：输入法切换到英文后再运行】\n"
                                                   "1、打开PADS Layout->打开对应需要核对的pcb文件->导出相应的excel表格->在excel表格最前面增加一列名为number，值为从1递增到最后一行\n"
                                                   "2、PADS Layout->ctrl+alt+c打开颜色设置->\n"
                                                   "    A、先抓取Top层数据：\n"
                                                   "    勾选对象类型：参考编号、顶面、底面\n"
                                                   "    勾选层：Top、Silkscreen Top、Assembly Drawing Top\n"
                                                   "    B、再抓取Bottom层数据：\n"
                                                   "    勾选对象类型：参考编号、顶面、底面\n"
                                                   "    勾选层：Bottom、Silkscreen Bottom、Assembly Drawing Bottom\n"
                                                   "3、选择当前工作表excel文件\n"
                                                   "4、选择当前抓取的层级：Top还是Bottom\n"
                                                   "5、点击开始运行，切换到PADS Layout界面，等待抓取完成\n"
                                                   "6、逐步完成全部的抓取"))
        self.layerChooseCombox.setItemText(0, _translate("MainWindow", "Top"))
        self.layerChooseCombox.setItemText(1, _translate("MainWindow", "Bottom"))
        self.label.setText(_translate("MainWindow", "选择需要抓取的图层："))
        self.label_2.setText(_translate("MainWindow", "元件抓取工具使用说明："))
        self.label_3.setText(_translate("MainWindow", "选择Excel文件："))
        self.chooseFileButton.setText(_translate("MainWindow", "选择文件"))
        self.label_4.setText(_translate("MainWindow", "当前运行状态："))
        self.runningButton.setText(_translate("MainWindow", "运行按钮"))
        self.label_5.setText(_translate("MainWindow", "本次运行结果："))
