# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BadPointCheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 137)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 251, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label.setObjectName("label")
        self.buttonStartCheck = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStartCheck.setGeometry(QtCore.QRect(10, 110, 221, 23))
        self.buttonStartCheck.setObjectName("buttonStartCheck")
        self.lable_Status = QtWidgets.QLabel(self.centralwidget)
        self.lable_Status.setGeometry(QtCore.QRect(160, 10, 51, 20))
        self.lable_Status.setObjectName("lable_Status")
        self.buttonGetPictureFolder = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetPictureFolder.setGeometry(QtCore.QRect(10, 80, 221, 23))
        self.buttonGetPictureFolder.setObjectName("buttonGetPictureFolder")
        MainWindow.setCentralWidget(self.centralwidget)

        self.buttonGetPictureFolder.clicked.connect(self.getFolderPath)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def getFolderPath(self):
        picture_folder = QFileDialog.getExistingDirectory()
        self.lable_Status.setText(picture_folder)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "坏点检测软件"))
        self.buttonStartCheck.setText(_translate("MainWindow", "开始检测"))
        self.lable_Status.setText(_translate("MainWindow", "状态："))
        self.buttonGetPictureFolder.setText(_translate("MainWindow", "选择待检测图片文件夹"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
