# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendarWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 421, 311))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setText("获取当前系统时间")
        self.button.setGeometry(QtCore.QRect(0, 309, 422, 32))

        self.calendarWidget.selectionChanged.connect(self.getDate)
        self.button.clicked.connect(self.getCurrentDateAndTime)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalendarWidget日历控件"))

    def getDate(self):
        date = self.calendarWidget.selectedDate()
        year = date.year()
        month = date.month()
        day = date.day()
        QMessageBox.information(self.MainWindow, "日历选择器", "当前选择的日期是：{}年{}月{}日".format(year, month, day))

    def getCurrentDateAndTime(self):
        datetime = QtCore.QDateTime.currentDateTime().date().month()
        date = QtCore.QDate.currentDate().month()
        time = QtCore.QTime().currentTime().second()
        QMessageBox.information(self.MainWindow, "获取当前系统日期时间",
                                "DateTime:{}\nDate:{}\nTime:{}".format(datetime, date, time))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
