# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 170)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 85, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(140, 10, 85, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(260, 10, 85, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(260, 40, 85, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(140, 40, 85, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 40, 85, 21))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(260, 70, 85, 21))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(140, 70, 85, 21))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 70, 85, 21))
        self.checkBox_9.setObjectName("checkBox_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 321, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.getSelect)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "复选框checkBox"))
        self.checkBox.setText(_translate("MainWindow", "one"))
        self.checkBox_2.setText(_translate("MainWindow", "two"))
        self.checkBox_3.setText(_translate("MainWindow", "three"))
        self.checkBox_4.setText(_translate("MainWindow", "six"))
        self.checkBox_5.setText(_translate("MainWindow", "five"))
        self.checkBox_6.setText(_translate("MainWindow", "four"))
        self.checkBox_7.setText(_translate("MainWindow", "nine"))
        self.checkBox_8.setText(_translate("MainWindow", "eight"))
        self.checkBox_9.setText(_translate("MainWindow", "seven"))
        self.pushButton.setText(_translate("MainWindow", "number set"))

    def getSelect(self):
        selected_number = ""
        if self.checkBox.isChecked():
            selected_number += "\n" + self.checkBox.text()
        if self.checkBox_2.isChecked():
            selected_number += "\n" + self.checkBox_2.text()
        if self.checkBox_3.isChecked():
            selected_number += "\n" + self.checkBox_3.text()
        if self.checkBox_4.isChecked():
            selected_number += "\n" + self.checkBox_4.text()
        if self.checkBox_5.isChecked():
            selected_number += "\n" + self.checkBox_5.text()
        if self.checkBox_6.isChecked():
            selected_number += "\n" + self.checkBox_6.text()
        if self.checkBox_7.isChecked():
            selected_number += "\n" + self.checkBox_7.text()
        if self.checkBox_8.isChecked():
            selected_number += "\n" + self.checkBox_8.text()
        QMessageBox.information(self.MainWindow, "号码选择!", "当前选中的数字有：" + selected_number, QMessageBox.Ok)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
