# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customerLoading.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 300)
        MainWindow.setMaximumSize(QtCore.QSize(333, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.loading.setGeometry(QtCore.QRect(0, 0, 333, 243))
        self.loading.setObjectName("loading")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 243, 111, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(222, 243, 111, 26))
        self.pushButton_2.setObjectName("pushButton_2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.start_loading)
        self.pushButton_2.clicked.connect(self.stop_loading)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loading.setText(_translate("MainWindow", "LOADING……"))
        self.pushButton.setText(_translate("MainWindow", "Start Loading"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop Loading"))

    def start_loading(self):
        # 此处不应该放在这里初始化，这里是控制函数
        self.gif = QtGui.QMovie("./loading.gif")
        self.loading.setMovie(self.gif)
        if self.gif.state() == self.gif.NotRunning:
            print(str(self.gif.state()))
            print(str(self.gif.NotRunning))
            self.gif.start()

    def stop_loading(self):
        if self.gif.state() == self.gif.Running:
            self.gif.stop()
            self.loading.clear()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
