# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontSizeChangeQSlider.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 504)
        MainWindow.setMinimumSize(QtCore.QSize(621, 504))
        MainWindow.setMaximumSize(QtCore.QSize(621, 504))
        MainWindow.setBaseSize(QtCore.QSize(621, 504))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(621, 504))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 561, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setProperty("value", 0)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(580, 50, 31, 441))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(5)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider.setProperty("value", 0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 571, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fontChangeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.fontChangeLabel.setGeometry(QtCore.QRect(250, 240, 111, 20))
        self.fontChangeLabel.setMinimumSize(QtCore.QSize(564, 443))
        self.fontChangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fontChangeLabel.setMaximumSize(QtCore.QSize(564, 443))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.fontChangeLabel.setFont(font)
        self.fontChangeLabel.setObjectName("fontChangeLabel")
        self.horizontalLayout.addWidget(self.fontChangeLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        # self.horizontalSlider.valueChanged.connect(lambda: self.setFontSizeUI(self.horizontalSlider))
        # self.verticalSlider.valueChanged.connect(lambda: self.setFontSizeUI(self.verticalSlider))
        self.horizontalSlider.valueChanged.connect(partial(self.setFontSizeUI, self.horizontalSlider))
        self.verticalSlider.valueChanged.connect(partial(self.setFontSizeUI, self.verticalSlider))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fontChangeLabel.setText(_translate("MainWindow", "敢想敢为，注重细节"))

    def setFontSizeUI(self, slider):
        if slider == self.horizontalSlider:
            value = self.horizontalSlider.value()
            self.verticalSlider.setValue(value)
        elif slider == self.verticalSlider:
            value = self.verticalSlider.value()
            self.horizontalSlider.setValue(value)
        self.fontChangeLabel.setFont(QtGui.QFont("等线", value))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
