# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontSizeChangeQSlider_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 504)
        MainWindow.setMinimumSize(QtCore.QSize(621, 504))
        MainWindow.setMaximumSize(QtCore.QSize(621, 504))
        MainWindow.setBaseSize(QtCore.QSize(621, 504))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(621, 504))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 561, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(580, 50, 31, 441))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(5)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 571, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fontChangeLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.fontChangeLabel_2.setMinimumSize(QtCore.QSize(10, 10))
        self.fontChangeLabel_2.setMaximumSize(QtCore.QSize(564, 443))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.fontChangeLabel_2.setFont(font)
        self.fontChangeLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fontChangeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fontChangeLabel_2.setObjectName("fontChangeLabel_2")
        self.horizontalLayout_2.addWidget(self.fontChangeLabel_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fontChangeLabel_2.setText(_translate("MainWindow", "敢想敢为，注重细节"))
