# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        # 设置窗口大小后，再设定MaximumSize即可固定大小不变
        MainWindow.resize(405, 253)
        MainWindow.setMaximumSize(QtCore.QSize(405, 253))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 0, 281, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(0, 0, 61, 261))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_2.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(340, 0, 71, 261))
        self.progressBar_3.setLayoutDirection(Qt.RightToLeft)
        # 竖直进度条需要设置是否反转进度条显示方向，setInvertedAppearance()为true时，进度条默认：从左至右或从上至下，为false时，从右至左或从下至上
        self.progressBar_3.setInvertedAppearance(True)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_3.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(60, 200, 281, 61))
        self.progressBar_4.setLayoutDirection(Qt.RightToLeft)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 110, 81, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QtCore.QBasicTimer()

        self.pushButton.clicked.connect(self.timer_running)

    def timer_running(self):
        if self.timer.isActive():
            self.timer.stop()
            self.pushButton.setText("开始")
            self.progressBar.setMaximum(100)
            self.progressBar_2.setMaximum(100)
            self.progressBar_3.setMaximum(100)
            self.progressBar_4.setMaximum(100)
        else:
            self.timer.start(100, self.MainWindow)
            self.pushButton.setText("停止")
            # 设置4个进度条的最大值和最小值都为0，以便显示循环滚动效果
            self.progressBar.setMaximum(0)
            self.progressBar.setMinimum(0)
            self.progressBar_2.setMaximum(0)
            self.progressBar_2.setMinimum(0)
            self.progressBar_3.setMaximum(0)
            self.progressBar_3.setMinimum(0)
            self.progressBar_4.setMaximum(0)
            self.progressBar_4.setMinimum(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开始"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
