# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qMenuBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox, QAction


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 394)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 595, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action123_2 = QtWidgets.QAction(MainWindow)
        self.action123_2.setObjectName("action123_2")
        self.action = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("doughnut.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon)
        self.action.setObjectName("action")
        self.actionEXCEL = QtWidgets.QAction(MainWindow)
        self.actionEXCEL.setIcon(icon)
        self.actionEXCEL.setObjectName("actionEXCEL")
        self.actionWORD = QtWidgets.QAction(MainWindow)
        self.actionWORD.setIcon(icon)
        self.actionWORD.setObjectName("actionWORD")
        self.actionLENOVO = QtWidgets.QAction(MainWindow)
        self.actionLENOVO.setIcon(icon)
        self.actionLENOVO.setObjectName("actionLENOVO")
        self.actionMACBOOK = QtWidgets.QAction(MainWindow)
        self.actionMACBOOK.setIcon(icon)
        self.actionMACBOOK.setObjectName("actionMACBOOK")
        self.actionCASE1 = QtWidgets.QAction(MainWindow)
        self.actionCASE1.setIcon(icon)
        self.actionCASE1.setObjectName("actionCASE1")
        self.actionCASE2 = QtWidgets.QAction(MainWindow)
        self.actionCASE2.setIcon(icon)
        self.actionCASE2.setObjectName("actionCASE2")
        self.actionCASE3 = QtWidgets.QAction(MainWindow)
        self.actionCASE3.setIcon(icon)
        self.actionCASE3.setObjectName("actionCASE3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.actionEXCEL)
        self.menu.addAction(self.actionWORD)
        self.menu_2.addAction(self.actionLENOVO)
        self.menu_2.addAction(self.actionMACBOOK)
        self.menu_3.addAction(self.actionCASE1)
        self.menu_3.addAction(self.actionCASE2)
        self.menu_3.addAction(self.actionCASE3)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        # 单独菜单项triggered
        self.action.triggered.connect(self.getActionTitle)
        # 所有菜单项triggered
        self.menu.triggered[QAction].connect(self.getCurrentTitle)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # 所有菜单项triggered
    def getCurrentTitle(self, q):
        QMessageBox.information(self.MainWindow, "Tip",
                                "You choose menu item is {}".format(q.text()), QMessageBox.Ok)

    # 单独菜单项triggered
    def getActionTitle(self):
        QMessageBox.information(self.MainWindow, "Tip",
                                "You choose menu item is {}".format(self.action.text()), QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "计算机"))
        self.menu_3.setTitle(_translate("MainWindow", "查看"))
        self.action123.setText(_translate("MainWindow", "123"))
        self.action123_2.setText(_translate("MainWindow", "123 "))
        self.action.setText(_translate("MainWindow", "PPT(&N)"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionEXCEL.setText(_translate("MainWindow", "EXCEL(&E)"))
        self.actionEXCEL.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionWORD.setText(_translate("MainWindow", "WORD(&W)"))
        self.actionWORD.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionLENOVO.setText(_translate("MainWindow", "LENOVO"))
        self.actionMACBOOK.setText(_translate("MainWindow", "MACBOOK"))
        self.actionCASE1.setText(_translate("MainWindow", "CASE1"))
        self.actionCASE2.setText(_translate("MainWindow", "CASE2"))
        self.actionCASE3.setText(_translate("MainWindow", "CASE3"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
