# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qMessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QInputDialog, QFontDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 291)
        MainWindow.setMaximumSize(QtCore.QSize(497, 291))
        MainWindow.setMinimumSize(QtCore.QSize(497, 291))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.pushButton1.setObjectName("pushButton1")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 481, 201))
        self.listWidget.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.bindList)
        self.pushButton1.clicked.connect(self.showDialog)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def bindList(self):
        dir = QFileDialog()
        dir.setFileMode(QFileDialog.ExistingFiles)
        dir.setDirectory("D:\\")
        dir.setNameFilter("图片文件(*.jpg *.png *.bmp *.ico *.gif)")
        if dir.exec_():
            self.listWidget.addItems(dir.selectedFiles())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "添加文件"))
        self.pushButton1.setText(_translate("MainWindow", "Test"))

    def showDialog(self):
        # QMessageBox.information(mainWindow, "Information", "This is information Dialog",
        #                         QMessageBox.Ok | QMessageBox.No | QMessageBox.Yes
        #                         | QMessageBox.Abort | QMessageBox.Retry | QMessageBox.Ignore
        #                         | QMessageBox.Close | QMessageBox.Cancel |
        #                         QMessageBox.Open | QMessageBox.Save)
        # QMessageBox.question(mainWindow, "Question", "This is question Dialog", QMessageBox.Ok)
        # QMessageBox.warning(mainWindow, "Warning", "This is warning Dialog", QMessageBox.Ok)
        # QMessageBox.critical(mainWindow, "Critical", "This is critical Dialog", QMessageBox.Ok)
        # QMessageBox.about(mainWindow, "About", "This is about Dialog")
        # print(QFileDialog.getOpenFileName())
        # print(QFileDialog.getOpenFileNames())
        # print(QFileDialog.getSaveFileName())
        # print(QFileDialog.getExistingDirectory())
        # print(QFileDialog.getSaveFileName())
        # text, flag = QInputDialog.getText(mainWindow, "Input dialog", "Please input content:")
        # self.listWidget.addItems(["text: {}".format(text), "flag：{}".format(flag)])
        # text, flag = QInputDialog.getItem(mainWindow, "Input dialog", "Get Item", ["1", "2", "3"])
        # self.listWidget.addItems(["text: {}".format(text), "flag：{}".format(flag)])
        # nputValue, flag = QInputDialog.getInt(mainWindow, "Input dialog", "Get Int", 255, 0, 512, 1)
        # self.listWidget.addItems(["text: {}".format(nputValue), "flag：{}".format(flag)])
        # inputValue, flag = QInputDialog.getDouble(mainWindow, "Input dialog", "Get Double", 255.255, 0.1, 512.512, 3)
        # self.listWidget.addItems(["text: {}".format(inputValue), "flag：{}".format(flag)])
        font, flag = QFontDialog.getFont()
        self.listWidget.addItems(["font: {}".format(font), "flag：{}".format(flag)])


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
