# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qToolBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setMaximumSize(500, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        # 单击QAction的对象 - Toolbar会根据Action返回的currentIndexChanged信号来定位当前是哪一个Action操作
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.addSeparator()
        # self.toolBar.addAction(QtGui.QIcon("./doughnut.ico"), "甜甜圈1")
        self.candyCircle1 = QtWidgets.QAction(QtGui.QIcon("./doughnut.ico"), "甜甜圈1")
        self.toolBar.addAction(self.candyCircle1)
        self.toolBar.addSeparator()
        self.candyCircle2 = QtWidgets.QAction(QtGui.QIcon("./doughnut.ico"), "甜甜圈2")

        self.toolBar.addAction(self.candyCircle2)
        self.toolBar.addSeparator()

        self.combox = QtWidgets.QComboBox()
        peopleList = ["视熙科技", "CRLF", "QToolBar", "QMenu", "甜甜圈呀"]
        self.combox.addItems(peopleList)
        self.toolBar.addWidget(self.combox)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(QtWidgets.QLabel("这个工具栏可以放好多好多东西的"))

        self.toolBar.actionTriggered[QtWidgets.QAction].connect(self.getValue)

        self.toolBar.setIconSize(QtCore.QSize(20, 20))

        self.candyCircle1.triggered.connect(self.isCandy)
        self.candyCircle2.triggered.connect(self.isCandy)
        self.combox.currentIndexChanged.connect(self.whichCareer)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def getValue(self, t):
        QMessageBox.information(self.MainWindow, "OK", "See {}".format(t.text()), QMessageBox.Ok)

    def isCandy(self):
        QMessageBox.information(self.MainWindow, "Look", "This is Candy window", QMessageBox.Ok)

    def whichCareer(self):
        QMessageBox.information(self.MainWindow, "That", "职位：{}".format(self.combox.currentText()), QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
