# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radioButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 238)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 60, 16))
        self.label_2.setObjectName("label_2")
        self.loginPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginPushButton.setGeometry(QtCore.QRect(60, 170, 81, 26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginPushButton.setIcon(icon)
        self.loginPushButton.setObjectName("loginPushButton")
        self.userNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.userNameLineEdit.setGeometry(QtCore.QRect(120, 50, 181, 22))
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.exitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitPushButton.setGeometry(QtCore.QRect(200, 170, 81, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitPushButton.setIcon(icon1)
        self.exitPushButton.setObjectName("exitPushButton")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(120, 100, 181, 22))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.administratorRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.administratorRadioButton.setGeometry(QtCore.QRect(60, 130, 97, 21))
        self.administratorRadioButton.setObjectName("administratorRadioButton")
        self.simpleUserRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.simpleUserRadioButton.setGeometry(QtCore.QRect(200, 130, 97, 21))
        self.simpleUserRadioButton.setObjectName("simpleUserRadioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.administratorRadioButton.setChecked(True)
        self.administratorRadioButton.toggled.connect(self.selectUser)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "单选按钮RadioButton"))
        self.label_3.setText(_translate("MainWindow", "密码："))
        self.label.setText(_translate("MainWindow", "系统登录"))
        self.label_2.setText(_translate("MainWindow", "用户名："))
        self.loginPushButton.setText(_translate("MainWindow", "登录"))
        self.exitPushButton.setText(_translate("MainWindow", "退出"))
        self.administratorRadioButton.setText(_translate("MainWindow", "管理员"))
        self.simpleUserRadioButton.setText(_translate("MainWindow", "普通用户"))

    def selectUser(self):
        if self.administratorRadioButton.isChecked():
            QMessageBox.information(self.MainWindow, "权限！", "当前权限级别为：" + self.administratorRadioButton.text(),
                                    QMessageBox.Ok)
        elif self.simpleUserRadioButton.isChecked():
            QMessageBox.information(self.MainWindow, "权限！", "当前权限级别为：" + self.simpleUserRadioButton.text(),
                                    QMessageBox.Ok)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
