# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QTreeWidgetItem


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.MainWindow = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.treeWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.treeWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.setHeaderLabels(["姓名", "职务"])
        root = QTreeWidgetItem(self.treeWidget)
        root.setText(0, "组织架构")

        dict_data = {"任正非": "华为董事长", "马云": "阿里巴巴创始人", "马化腾": "腾讯CEO", "李彦宏": "百度CEO", "董明珠": "格力董事长"}
        for key, value in dict_data.items():
            child = QTreeWidgetItem(root)
            child.setText(0, key)
            child.setText(1, value)
            child.setCheckState(0, QtCore.Qt.Unchecked)
            if key == "任正非":
                child.setIcon(0, QIcon("../images_file/huawei.ico"))
            elif key == "马云":
                child.setIcon(0, QIcon("../images_file/alibaba.ico"))
            elif key == "马化腾":
                child.setIcon(0, QIcon("../images_file/tencent.ico"))
            elif key == "李彦宏":
                child.setIcon(0, QIcon("../images_file/baidu.ico"))
            elif key == "董明珠":
                child.setIcon(0, QIcon("../images_file/geree.ico"))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.addTopLevelItem(root)
        self.treeWidget.expandAll()
        self.treeWidget.clicked.connect(self.getTreeItemText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

    def getTreeItemText(self):
        item = self.treeWidget.currentItem()
        QtWidgets.QMessageBox.information(self.MainWindow, "Tips",
                                          "You choose the company {} and Leader {}".format(item.text(1), item.text(0),
                                                                                           QtWidgets.QMessageBox.Ok))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
