# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeViewQStrandardItemModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 323)
        MainWindow.setMaximumSize(QtCore.QSize(442, 323))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(442, 323))
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(5, 1, 431, 321))
        self.treeView.setMaximumSize(QtCore.QSize(442, 16777215))
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)

        self.customizationModel()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def customizationModel(self):
        model = QtGui.QStandardItemModel()
        model.setHorizontalHeaderLabels(["测试点", "测试用例数量", "Manpower"])

        # 一级节点内容
        testPoints = ["基本功能测试", "功能交互测试", "功能压力测试", "UI测试", "功能异常值测试", "用户稳定性测试"]
        testCaseCount = [80, 21, 7, 2, 7, 2]
        manpower = [1, 1, 1, 1, 1, 1]

        for i in range(0, len(testPoints)):
            tp = QtGui.QStandardItem(testPoints[i])
            tcc = QtGui.QStandardItem(str(testCaseCount[i]))
            mp = QtGui.QStandardItem(str(manpower[i]))
            model.appendRow([tp, tcc, mp])

        # 二级节点内容
        testCaseTitleLabel = ["测试类型", "模块"]
        self.treeView.setModel(model)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon("./doughnut.ico"))
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
